### PR TITLE
Add mkdocstrings autodoc recipe

### PR DESCRIPTION
**Pull request by johnthagen**
Follow on to #82

- https://mkdocstrings.github.io/recipes/

### CODE REVIEW

**Comment by pawamoy** [comment]
Try to put mkdocstrings plugin after gen files and literate nav (just guessing)

**Comment by johnthagen** [comment]
> Try to put mkdocstrings plugin after gen files and literate nav (just guessing)

Same error after trying:

```yaml
plugins:
  - search
  # Autodoc configuration.
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_if_no_docstring: true
            show_signature_annotations: true
      watch:
        - src
```

**Comment by johnthagen** [comment]
To reproduce:

```bash
(venv) $ python -m pip install tox
(venv) $ tox -e docs-serve
```

**Comment by pawamoy** [comment]
OK, there's actually an error, you should have told me:

```
ERROR    -  mkdocstrings: fact.__init__ could not be found
ERROR    -  Error reading page 'reference/fact/__init__.md':
ERROR    -  Could not collect 'fact.__init__'
```

**Comment by pawamoy** [comment]
Kay I'll push a docs update, this should work better for Python :slightly_smiling_face:

**Pull request merged**
